version: '3.8'
services:
 web:
    build: .
    command: gunicorn -c mainapp/gunicorn_config.py mainapp.wsgi:application
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - nginx
    networks:
      - web_network

 nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - web_network

networks:
 web_network:
    driver: bridge
