version: "3.8"
services:
 web:
    build: .
    restart: unless-stopped
    command: gunicorn mainapp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env

