# Generated by Django 4.2.9 on 2024-02-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deaths',
            field=models.IntegerField(default=0, verbose_name='количества смертей пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='obstacle_collisions',
            field=models.IntegerField(default=0, verbose_name='количества столкновений пользователя'),
        ),
    ]
