# Generated by Django 4.2.9 on 2024-02-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_user_deaths_user_obstacle_collisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='boosters',
            field=models.JSONField(default={}, verbose_name='бустеры пользователя'),
        ),
    ]
