# Generated by Django 4.2.9 on 2024-02-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_user_boosters'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unlocked_characters',
            field=models.JSONField(blank=True, default={}, verbose_name='персонажи пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='boosters',
            field=models.JSONField(blank=True, default={}, verbose_name='бустеры пользователя'),
        ),
        migrations.AlterField(
            model_name='userseasonscore',
            name='season_high_score',
            field=models.IntegerField(default=0, verbose_name='сумма очков пользователя в сезоне'),
        ),
    ]
