# Generated by Django 4.2.9 on 2024-02-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_user_unlocked_characters_alter_user_boosters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='текущий сезон'),
        ),
    ]
