# Generated by Django 4.2.9 on 2024-03-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_season_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название')),
                ('description', models.CharField(max_length=500, verbose_name='описание')),
                ('type', models.CharField(choices=[('Invincibility', 'Invincibility'), ('Speed', 'Speed'), ('Magnet', 'Magnet')], max_length=50)),
                ('price', models.IntegerField(verbose_name='цена')),
            ],
            options={
                'verbose_name': 'Бустер',
                'verbose_name_plural': 'Бустеры',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='имя')),
                ('description', models.CharField(max_length=500, verbose_name='описание')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('game_over_messages', models.JSONField(blank=True, default={}, verbose_name='game_over_messages')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='selected_character',
            field=models.CharField(default='DefaultCharacter', max_length=250, verbose_name='выбранный персонаж'),
        ),
        migrations.AlterField(
            model_name='user',
            name='boosters',
            field=models.JSONField(blank=True, default={'Invincibility': 0, 'Magnet': 0, 'Speed': 0}, verbose_name='бустеры'),
        ),
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=0, verbose_name='количество монет'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deaths',
            field=models.IntegerField(default=0, verbose_name='количества смертей'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='obstacle_collisions',
            field=models.IntegerField(default=0, verbose_name='количества столкновений'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unlocked_characters',
            field=models.JSONField(blank=True, default=['DefaultCharacter', 'Girl'], verbose_name='персонажи пользователя'),
        ),
    ]
