# Generated by Django 4.2.9 on 2024-03-06 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_booster_character_user_selected_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='string_id',
            field=models.CharField(default='id', max_length=250, verbose_name='frontend id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='game_over_messages',
            field=models.JSONField(blank=True, verbose_name='game_over_messages'),
        ),
        migrations.AlterField(
            model_name='season',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 12, 28, 52, 323773, tzinfo=datetime.timezone.utc), verbose_name='время окончания сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 12, 28, 52, 323773, tzinfo=datetime.timezone.utc), verbose_name='время начала сезона'),
        ),
    ]
