# Generated by Django 4.2.9 on 2024-03-06 18:51

import datetime
from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_character_string_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booster',
            name='type',
        ),
        migrations.AddField(
            model_name='booster',
            name='string_id',
            field=models.CharField(default='def', max_length=250, verbose_name='frontend type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='game_over_messages',
            field=models.JSONField(blank=True, default='', verbose_name='game_over_messages'),
        ),
        migrations.AlterField(
            model_name='season',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 18, 49, 20, 509460, tzinfo=datetime.timezone.utc), verbose_name='время окончания сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 18, 49, 20, 509460, tzinfo=datetime.timezone.utc), verbose_name='время начала сезона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='boosters',
            field=models.JSONField(blank=True, validators=[game.models.User.validate_json_keys], verbose_name='бустеры'),
        ),
    ]
