# Generated by Django 4.2.9 on 2024-03-10 13:43

import datetime
from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_booster_type_booster_string_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 13, 43, 14, 347885, tzinfo=datetime.timezone.utc), verbose_name='время окончания сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 10, 13, 43, 14, 347885, tzinfo=datetime.timezone.utc), verbose_name='время начала сезона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='boosters',
            field=models.JSONField(blank=True, default={}, validators=[game.models.User.validate_json_keys], verbose_name='бустеры'),
        ),
    ]
