# Generated by Django 4.2.9 on 2024-03-10 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_season_finish_date_alter_season_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(default='None', max_length=500, verbose_name='действительный refresh token'),
        ),
        migrations.AlterField(
            model_name='season',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 14, 41, 5, 565252, tzinfo=datetime.timezone.utc), verbose_name='время окончания сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 10, 14, 41, 5, 565252, tzinfo=datetime.timezone.utc), verbose_name='время начала сезона'),
        ),
    ]
