# Generated by Django 4.2.9 on 2024-03-10 16:54

import datetime
from django.db import migrations, models
import django_jsonform.models.fields
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_user_refresh_token_alter_season_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='game_over_messages',
            field=models.JSONField(blank=True, default=['message_1', 'message_2'], verbose_name='game_over_messages'),
        ),
        migrations.AlterField(
            model_name='season',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 16, 54, 17, 941710, tzinfo=datetime.timezone.utc), verbose_name='время окончания сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 10, 16, 54, 17, 941710, tzinfo=datetime.timezone.utc), verbose_name='время начала сезона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='boosters',
            field=django_jsonform.models.fields.JSONField(blank=True, default={}, validators=[game.models.User.validate_boosters], verbose_name='бустеры'),
        ),
    ]
