# Generated by Django 4.2.9 on 2024-03-10 20:46

import datetime
from django.db import migrations, models
import django_jsonform.models.fields
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_character_game_over_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='game_over_messages',
            field=django_jsonform.models.fields.JSONField(blank=True, default=['message_1', 'message_2'], verbose_name='game_over_messages'),
        ),
        migrations.AlterField(
            model_name='season',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 20, 46, 33, 250451, tzinfo=datetime.timezone.utc), verbose_name='время окончания сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 10, 20, 46, 33, 250451, tzinfo=datetime.timezone.utc), verbose_name='время начала сезона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unlocked_characters',
            field=django_jsonform.models.fields.JSONField(blank=True, default=['DefaultCharacter', 'Girl'], validators=[game.models.User.validate_characters], verbose_name='персонажи пользователя'),
        ),
    ]
