# Generated by Django 4.2.9 on 2024-03-13 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_character_game_over_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='finish_time',
            field=models.TimeField(default=datetime.datetime(1900, 1, 1, 23, 59, 50)),
        ),
        migrations.AddField(
            model_name='season',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='season',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 17, 34, 39, 775545, tzinfo=datetime.timezone.utc), verbose_name='дата окончания сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='number',
            field=models.IntegerField(default=0, verbose_name='номер сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 13, 17, 34, 39, 772543, tzinfo=datetime.timezone.utc), verbose_name='дата начала сезона'),
        ),
    ]
