# Generated by Django 4.2.9 on 2024-03-18 08:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_season_finish_time_season_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('image', models.ImageField(upload_to='ranks_images', verbose_name='изображение')),
                ('min_int_users', models.IntegerField(verbose_name='минимальное количество пользователей (целое число)')),
                ('min_percent_users', models.IntegerField(verbose_name='минимальное количество пользователей (проценты)')),
                ('front_download', models.BooleanField(default=False, verbose_name='картинка скачана фронтом')),
            ],
            options={
                'verbose_name': 'Ранг',
                'verbose_name_plural': 'Ранги',
            },
        ),
        migrations.AlterField(
            model_name='season',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 17, 8, 42, 32, 136988, tzinfo=datetime.timezone.utc), verbose_name='дата окончания сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='finish_time',
            field=models.TimeField(default=datetime.datetime(1900, 1, 1, 23, 59, 50), verbose_name='время окончания сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 8, 42, 32, 129699, tzinfo=datetime.timezone.utc), verbose_name='дата начала сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(1900, 1, 1, 0, 0), verbose_name='время начала сезона'),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.rank', verbose_name='ранг'),
        ),
    ]
