# Generated by Django 4.2.9 on 2024-03-18 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_rank_alter_season_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='rank',
            name='number',
            field=models.IntegerField(default=0, verbose_name='ранг по счету'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='season',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 17, 8, 49, 7, 922146, tzinfo=datetime.timezone.utc), verbose_name='дата окончания сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 8, 49, 7, 917144, tzinfo=datetime.timezone.utc), verbose_name='дата начала сезона'),
        ),
    ]
