# Generated by Django 4.2.9 on 2024-03-18 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_user_options_rank_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='front_download',
        ),
        migrations.AlterField(
            model_name='season',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 17, 12, 20, 21, 977008, tzinfo=datetime.timezone.utc), verbose_name='дата окончания сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 12, 20, 21, 969829, tzinfo=datetime.timezone.utc), verbose_name='дата начала сезона'),
        ),
    ]
