# Generated by Django 4.2.9 on 2024-03-20 08:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_remove_rank_front_download_alter_season_finish_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='prize',
        ),
        migrations.AlterField(
            model_name='season',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 19, 8, 45, 29, 886536, tzinfo=datetime.timezone.utc), verbose_name='дата окончания сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 20, 8, 45, 29, 878295, tzinfo=datetime.timezone.utc), verbose_name='дата начала сезона'),
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(verbose_name='монеты')),
                ('characters', django_jsonform.models.fields.JSONField(blank=True, default=[], validators=[game.models.Prize.validate_characters], verbose_name='персонажи')),
                ('boosters', django_jsonform.models.fields.JSONField(blank=True, default={}, validators=[game.models.Prize.validate_boosters], verbose_name='бустеры')),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.rank', verbose_name='ранг')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.season', verbose_name='сезон')),
            ],
        ),
    ]
