# Generated by Django 4.2.9 on 2024-03-20 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_remove_season_prize_alter_season_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prize',
            options={'verbose_name': 'Приз', 'verbose_name_plural': 'Призы'},
        ),
        migrations.AlterField(
            model_name='prize',
            name='boosters',
            field=django_jsonform.models.fields.JSONField(blank=True, default={'Speed': 0}, validators=[game.models.User.validate_boosters], verbose_name='бустеры'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.rank', verbose_name='ранг'),
        ),
        migrations.AlterField(
            model_name='season',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 19, 9, 1, 55, 566232, tzinfo=datetime.timezone.utc), verbose_name='дата окончания сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 20, 9, 1, 55, 560056, tzinfo=datetime.timezone.utc), verbose_name='дата начала сезона'),
        ),
    ]
