# Generated by Django 4.2.9 on 2024-03-20 15:38

import datetime
from django.db import migrations, models
import django_jsonform.models.fields
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_prize_options_alter_prize_boosters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='boosters',
            field=django_jsonform.models.fields.JSONField(blank=True, default={'Invincibility': 0, 'Magnet': 0, 'Speed': 0}, validators=[game.models.User.validate_boosters], verbose_name='бустеры'),
        ),
        migrations.AlterField(
            model_name='season',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 19, 15, 38, 25, 440624, tzinfo=datetime.timezone.utc), verbose_name='дата окончания сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 20, 15, 38, 25, 437622, tzinfo=datetime.timezone.utc), verbose_name='дата начала сезона'),
        ),
    ]
