# Generated by Django 4.2.9 on 2024-03-20 16:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_alter_prize_boosters_alter_season_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 19, 16, 7, 45, 709768, tzinfo=datetime.timezone.utc), verbose_name='дата окончания сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 20, 16, 7, 45, 706765, tzinfo=datetime.timezone.utc), verbose_name='дата начала сезона'),
        ),
        migrations.CreateModel(
            name='SuperPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название')),
                ('image_preview', models.ImageField(upload_to='super_prize_images', verbose_name='превью картинка')),
                ('image_gift', models.ImageField(upload_to='super_prize_images', verbose_name='картинка подарка')),
                ('description', models.TextField(max_length=500, verbose_name='описание')),
                ('burns_down_date', models.DateField(verbose_name='дата когда сгорает приз')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.season', verbose_name='сезон')),
            ],
            options={
                'verbose_name': 'Супер приз',
                'verbose_name_plural': 'Супер призы',
            },
        ),
        migrations.CreateModel(
            name='PrizeTop3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_number', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], verbose_name='место')),
                ('coins', models.IntegerField(verbose_name='монеты')),
                ('characters', django_jsonform.models.fields.JSONField(blank=True, default=[], validators=[game.models.User.validate_characters], verbose_name='персонажи')),
                ('boosters', django_jsonform.models.fields.JSONField(blank=True, default={'Invincibility': 0, 'Magnet': 0, 'Speed': 0}, validators=[game.models.User.validate_boosters], verbose_name='бустеры')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.rank', verbose_name='ранг')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.season', verbose_name='сезон')),
            ],
            options={
                'verbose_name': 'Приз для ТОП 3',
                'verbose_name_plural': 'Призы для ТОП 3',
            },
        ),
    ]
