# Generated by Django 4.2.9 on 2024-03-20 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_season_finish_date_alter_season_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prizetop3',
            name='rank',
        ),
        migrations.AlterField(
            model_name='prizetop3',
            name='top_number',
            field=models.IntegerField(choices=[(1, 'FIRST'), (2, 'SECOND'), (3, 'THIRD')], verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='season',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 19, 16, 11, 59, 695491, tzinfo=datetime.timezone.utc), verbose_name='дата окончания сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 20, 16, 11, 59, 692489, tzinfo=datetime.timezone.utc), verbose_name='дата начала сезона'),
        ),
    ]
