# Generated by Django 4.2.9 on 2024-03-21 07:55

import datetime
from django.db import migrations, models
import django_jsonform.models.fields
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_remove_prizetop3_rank_alter_prizetop3_top_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='image_hash',
            field=models.CharField(default='passhesh', max_length=300, verbose_name='хэш изображения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prize',
            name='boosters',
            field=django_jsonform.models.fields.JSONField(blank=True, default={'Magnet': 0, 'Speed': 0, 'Test': 0}, validators=[game.models.User.validate_boosters], verbose_name='бустеры'),
        ),
        migrations.AlterField(
            model_name='prizetop3',
            name='boosters',
            field=django_jsonform.models.fields.JSONField(blank=True, default={'Magnet': 0, 'Speed': 0, 'Test': 0}, validators=[game.models.User.validate_boosters], verbose_name='бустеры'),
        ),
        migrations.AlterField(
            model_name='prizetop3',
            name='top_number',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='season',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 20, 7, 54, 47, 257172, tzinfo=datetime.timezone.utc), verbose_name='дата окончания сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 7, 54, 47, 251000, tzinfo=datetime.timezone.utc), verbose_name='дата начала сезона'),
        ),
    ]
