# Generated by Django 4.2.9 on 2024-03-21 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_rank_image_hash_alter_prize_boosters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='image_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 11, 13, 48, 613603, tzinfo=datetime.timezone.utc), verbose_name='когда загружена картинка'),
        ),
        migrations.AlterField(
            model_name='season',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 20, 11, 13, 48, 621836, tzinfo=datetime.timezone.utc), verbose_name='дата окончания сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 11, 13, 48, 619789, tzinfo=datetime.timezone.utc), verbose_name='дата начала сезона'),
        ),
    ]
